action_id: trunk-share-with-everyone
date: 2023-08-27 01:11:54
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 127
  out: ""
  err: "[08-27 04:11:54] [terminate_handler.cc:29] std::terminate called with active exception:\ntrunk_cli_version: 1.14.1\ntitle: Internal trunk error occurred. Please report this issue to us @ https://slack.trunk.io\nreport:\n  - \"Failed to open link directory: C:\\\\Users\\\\user\\\\Documents\\\\University\\\\.trunk\\\\out, error: 32\"\nexception_backtrace:\n  - (unknown)\n  - (unknown)\n  - (unknown)\n  - (unknown)\n  - (unknown)\n  - (unknown)\n  - (unknown)\n  - BaseThreadInitThunk\n  - RtlUserThreadStart\n\ncurrent_backtrace:\n  - (unknown)\n\n\r\n"
timestamp: 1693098714
full_timestamp:
  nanos: 696278000
  seconds: 1693098714
trunk_version: 1.14.1
